spring.application.name=naming-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.config.import=optional:configserver:

#service deregistration property for eviction : optional
#eureka.server.eviction-interval-timer-in-ms=60000