# Change only this value to choose which NintendoGames implementation Spring injects.
# Supported values: mario, super-contra
nintendo.game=super-contra
logging.level.org.springframework=debug
server.port=8081

