spring.application.name=spring-cloud-config-server
server.port=8888
#spring.cloud.config.server.git.uri=file:///Users/rangakaranam/Ranga/git/01.udemy-course-repos/spring-microservices-v2/03.microservices/git-localconfig-repo
spring.cloud.config.server.git.uri=file:///C:/D_Pratul/VSCode_workspace/sp_workspace/03.microservices/git-localconfig-repo
spring.cloud.config.server.git.default-label=master