spring.application.name=SpringBoot-test-1
server.port=8083
spring.profiles.active=dev
logging.level.org.springframework=error

currency-service.url=https://api.example.com/currency
currency-service.username=sample-user
currency-service.key=sample-api-key

management.endpoints.web.exposure.include=*