spring.application.name=currency-exchange
server.port=8000

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb
#SB4 , its done so that data.sql execution is deferred till DDLs are created based on JPA entity structure
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.config.import=optional:configserver:

#eureka lease properties : optional
#eureka.instance.lease-renewal-interval-in-seconds=30
#eureka.instance.lease-expiration-duration-in-seconds=90